### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by bobblkabb** [pseuudonym404/neverball-touch#2]
Having display trouble with Neverball 1.6.0-1 on a Nexus 4 device (Ubuntu Touch only, no android).
System: Ubuntu 14.10 (r19)

![screenshot20153128_093157110](https://cloud.githubusercontent.com/assets/7815101/7855072/05566638-051f-11e5-9fde-48ced6b2aa04.png)

**Comment by nikwen** [comment]
I am seeing this on my Nexus 4 as well. However, I'm on devel-proposed (15.10).

**Comment by popey** [comment]
I see similar corruption on Nexus 7. I would be inclined to file a bug against Mir.

**Comment by nikwen** [comment]
I think it's worth noting that when I tap the screen where the buttons are supposed to be, the app responds to that.

Here's the log output when I open the app:

```
phablet@ubuntu-phablet:~/.cache/upstart$ cat application-click-neverball.lb_neverball_1.6.0-1.log 
libust[3803/3805]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[3803/3805]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[3803/3806]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[3803/3806]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
[1432811798.732386] Loader: Loading modules from: /usr/lib/arm-linux-gnueabihf/mir/client-platform/
[1432811798.734340] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/mesa.so.2
[1432811798.738918] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/dummy.so
[1432811798.740993] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/android.so.2
shm_open() failed: Permission denied
shm_open() failed: Permission denied
Loading module: 'libubuntu_application_api_touch_mirclient.so.2.9.0'
Creating a window (768x1280, fullscreen)
Created a window (1, 768x1280, fullscreen)
Size change event (1, 768x1280)
```

**Comment by laurie-bradshaw** [comment]
I've been testing on 14.10 on my Aquaris.

I'd really like to fix this, but as I don't have any nexus devices, I can't really do much at the moment apart from answer questions if somebody else feels like having a go at fixing it.

**Comment by nikwen** [comment]
@pseuudonym404 You could try running your app in the emulator to see whether it works there. (If there's an option for that, choose a different resolution than the bq's one.)

**Comment by laurie-bradshaw** [comment]
I just successfully got neverball to run in the emulator (i386 build), with no graphical corruption.

I changed the code to load glTexGeniOES dynamically to solve link errors in the i386 build.

I don't know if that made any difference to nexus hw, but I'm going to clean that up a bit (it just assumes it'll work at the moment), and update the package.

**Comment by bobblkabb** [comment]
Unfortunately there's no difference to the previous version.

**Comment by nikwen** [comment]
Yes, sadly, it didn't change anything for me.
It could still be a Mir bug though.

**Comment by laurie-bradshaw** [comment]
I built a couple of the SDL tests, if you could try them and let me know the results?
Chessboard uses software rendering, to check if it's a window creation problem.

https://www.dropbox.com/s/ri1qw0xja7pnfdq/chessboard.lb_1.0-1_armhf.click
https://www.dropbox.com/s/t48lfztstkm8m95/gles.lb_1.0-1_armhf.click

**Comment by popey** [comment]
Gles demo on the nexus 7 2013.
http://people.canonical.com/~alan/screenshots/device-2015-05-29-165112.png
http://people.canonical.com/~alan/screenshots/device-2015-05-29-165216.png

Green banding rolling at the top.

SDL chessboard on same device:-

http://people.canonical.com/~alan/screenshots/device-2015-05-29-165249.png
http://people.canonical.com/~alan/screenshots/device-2015-05-29-165308.png

I'm still very much of the opinion that this is a Mir bug and should be filed at https://bugs.launchpad.net/mir/+bugs

**Comment by popey** [comment]
Same thing running on Meizu device.

http://people.canonical.com/~alan/screenshots/device-2015-05-29-165622.png
http://people.canonical.com/~alan/screenshots/device-2015-05-29-165628.png

http://people.canonical.com/~alan/screenshots/device-2015-05-29-165650.png
http://people.canonical.com/~alan/screenshots/device-2015-05-29-165657.png

**Comment by laurie-bradshaw** [comment]
It could also be an SDL bug, although given that it does work on some devices, mir does seem more likely.
Do you want to file the bug, or should I?

**Comment by popey** [comment]
Filed. https://bugs.launchpad.net/mir/+bug/1460149

**Comment by ghost** [comment]
Same with 1.6.0-3.

**Comment by nikwen** [comment]
Thanks for filing the bug report.

**Comment by laurie-bradshaw** [comment]
I just released an update with a possible workaround for nexus, is it actually working for anyone?

**Comment by popey** [comment]
Works on Nexus 7 2013! Nice one!

**Comment by laurie-bradshaw** [comment]
Thanks for letting me know. :)
I'll leave this bug open for a few days just in case it's not working for everyone.

**Comment by bobblkabb** [comment]
1.6.0-4 works now on Nexus 4.
Thanks a lot!

**Comment by nikwen** [comment]
Working perfectly on my Nexus 4. Thank you very much!

**Comment by zubozrout** [comment]
Yes, works flawlessly (both Neverball and Neverputt) on Nexus 7 LTE. Thank you :+1:

**Comment by popey** [comment]
@pseuudonym404 is it possible to get the source for the above chessboard and gles demos? They're helpful for testing sdl and mir :)

**Comment by laurie-bradshaw** [comment]
They're part of the SDL source, in the test directory. :)

I just built them manually with gcc in a click chroot.

**Comment by popey** [comment]
Ok thanks. I thought you may have tweaked them a little :)

**Comment by laurie-bradshaw** [comment]
I did use SDL_FULLSCREEN_DESKTOP instead of SDL_FULLSCREEN.
They do run without modifcation though. :)

**Comment by laurie-bradshaw** [comment]
Forgot to close this. :)
