### ISSUE TITLE
libs and binaries should be in arch specific folders

### ISSUE THREAD

**Issue by popey** [pseuudonym404/neverball-touch#3]
As per https://developer.ubuntu.com/en/start/platform/guides/app-confinement/

armhf libraries used by the game should be in ~/lib/arm-linux-gnueabihf
No need to set the LD_LIBRARY_PATH once you do that.
Will also need to move the binaries.

Net result being you could put a "fat" package in the store with armhf/i386/x86_64 binaries which work across x86 and armhf tablets.

**Comment by laurie-bradshaw** [comment]
Fixed, and i386 binaries added too.
