### ISSUE TITLE
Inhibit screensaver

### ISSUE THREAD

**Issue by merlijn-sebrechts** [pseuudonym404/neverball-touch#4]
Is it possible to inhibit the screensaver from kicking in while playing neverball?

**Comment by laurie-bradshaw** [comment]
Unfortunately, not from a click package.

It seems the only api to do this currently is via dbus, and click applications do not have permission to send the appropriate messages.

You can enter "powerd-cli display on" in a terminal as a workaround, and kill it when you're done.

**Comment by merlijn-sebrechts** [comment]
I filed a bug about this: https://bugs.launchpad.net/bugs/1460069

**Comment by laurie-bradshaw** [comment]
Fixed in current version. :)
