### ISSUE TITLE
App rotates off screen

### ISSUE THREAD

**Issue by popey** [pseuudonym404/neverball-touch#8]
Using a meizu mx4 running latest rc-proposed channel with rotation lock _off_ the app starts in landscape mode when phone held in portrait (which is fine). However as soon as you turn the phone to start playing, the game rotates 90 degrees away from you, so it's unplayable.

Workaround is to set rotation lock on. Better fix would probably be to set this in your .desktop file:-

X-Ubuntu-Supported-Orientations=portrait

**Comment by popey** [comment]
http://i.imgur.com/Ha86za3.png what it looks like.

**Comment by laurie-bradshaw** [comment]
Done. :)
