### ISSUE TITLE
Rotation wrong

### ISSUE THREAD

**Issue by mzanetti** [pseuudonym404/neverball-touch#9]
Currently the app locks to portrait and rotates the scene itself. This is messing up edge gestures on the phone.

Instead it should lock itself to landscape directly

**Comment by laurie-bradshaw** [comment]
Either way is wrong really, as the orientation can be changed in options.

I just added the desktop file parameter to stop the app from being rotated when tilting.

By messing up, do you mean gestures aren't on the edge you expect them to be or something else?

If it is that, could you try changing portrait to landscape in the neverball desktop file in ~/.local/share/click/hooks/desktop to check if that just changes the gesture edges.

If that has the desired results, I'll change it so it at least matches the default orientation.

**Comment by mzanetti** [comment]
Oh... I just found the orientation settings. In this case my suggestion is not the proper one too. I guess the proper one would be to dynamically adjust the shell according to what the user has set in the settings. However, Ubuntu doesn't support that yet. A more dynamic API is planned in the future tho.

For the current situation I'm not sure. On one hand I think it would make sense to have the setting in the desktop file to be the same as the default setting in the app (landscape), on the other I think if this can drift out of sync, it's probably better to keep shell's default.

What might be a good idea for now is to lock it to "primary" instead of landscape/portrait. That way, for example on a Nexus 7 it will be landscape by default (as the tablet's default ortientation is landscape) but it'll portrait on the phones.

Dunno. You decide. Feel free to close this bug as invalid then.

**Comment by laurie-bradshaw** [comment]
Locking to primary probably does make the most sense in lieu of a dynamic api.

I'm not particularly inclined to make people redownload just for that though, so next time there's something else to fix/update.

**Comment by mauk81** [comment]
locking to primary does not work with landscape devices (tablet/bq aquarius m10)
see app user reviews:

> https://uappexplorer.com/app/neverball.lb
> https://uappexplorer.com/app/neverputt.lb
